### ISSUE TITLE
ModuleNotFoundError: No module named 'digitalpy.core.security'

### ISSUE THREAD

**Issue by Hellikandra** [FreeTAKTeam/DigitalPy#47]
I am following this page to reset ssl certs : https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Troubleshooting/SocketIssue/

When I try this command :
`python3 -m digitalpy.core.security.crl_regen --ca-pem-path /usr/local/lib/python3.8/dist-packages/FreeTAKServer/certs/ca.pem --ca-key-path /usr/local/lib/python3.8/dist-packages/FreeTAKServer/certs/ca.key --crl-path /usr/local/lib/python3.8/dist-packages/FreeTAKServer/certs/FTS_CRL.json`

python return : 
`/usr/bin/python3: Error while finding module specification for 'digitalpy.core.security.crl_regen' (ModuleNotFoundError: No module named 'digitalpy.core.security')`

by looking in the `site-package`, the folder `security` does not exist.
by looking in source code in release tag : `security folder does not exist`
by looking in pypi website : the tar does not have the `security` folder.

**Comment by brothercorvo** [comment]
Are you using fts 2.0? In this case probably you have python 3.11

**Comment by Hellikandra** [comment]
FTS 1.9.5 and Python3.8
I also try in Python3.6 directly by using only `python3 -m digitalpy.core.security.crl_regen`. and python return the same error.

**Comment by brothercorvo** [comment]
The fix has been developed for fts 2.0. We have also tested it with 1.9.9.6 but you run a real old version and er suggest to update

**Comment by Hellikandra** [comment]
I am sorry but I do not understand the link between the error from python and modules/packages and the need to update FTS.

In my sens, python error which said `/usr/bin/python3: Error while finding module specification for 'digitalpy.core.security.crl_regen' (ModuleNotFoundError: No module named 'digitalpy.core.security')` is not linked to the version of FTS due to the fact that it's depend on the `DigitalPy` package and not FTS package.

**Comment by Hellikandra** [comment]
After doing some manipulation, digitalpy works only if I download directly from git and not from pip.

**Comment by brothercorvo** [comment]
This is strange because we use pip to install FTS

**Comment by brothercorvo** [comment]
@naman108 can you verify?

**Comment by naman108** [comment]
I've reproduced with the most recent version of digitalpy downloaded via pip. Even though the folder exists.

**Comment by naman108** [comment]
I can confirm that this is fixed in the current version of fts and can be executed as follows
```
(fts.venv) root@DevServer:~# python -m digitalpy.core.security.crl_regen --ca-pem-path /opt/fts/certs/ca.pem --ca-key-path /opt/fts/certs/ca.key --crl-path /opt/fts/certs/FTS_CRL.json
```
