### ISSUE TITLE
DigitalPy formatting and dependencies issue

### ISSUE THREAD

**Issue by iAcolyte** [FreeTAKTeam/DigitalPy#48]
Hello! I have an issue with FTS installation. 
If I fix it with autopep8, it can't resolve Catalog.
FTS-UI crashes because of missing requests.

Log below:

Cannot find CA file locally so generating one
Generating Key...
Generating Key...
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/telemetry, with error: inconsistent use of tabs and spaces in indentation (telemetry_facade.py, line 21)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/network, with error: unindent does not match any outer indentation level (network_facade.py, line 16)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/persistence, with error: module 'digitalpy.core.persistence.persistence_facade' has no attribute 'Persistence'
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/logic, with error: expected an indented block (logic_facade.py, line 22)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/translation, with error: expected an indented block (translation_facade.py, line 22)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/queries, with error: inconsistent use of tabs and spaces in indentation (queries_facade.py, line 21)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/util, with error: inconsistent use of tabs and spaces in indentation (util_facade.py, line 21)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/component_management, with error: module 'digitalpy.core.component_management.component_management_facade' has no attribute 'ComponentManagement'
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/zmanager, with error: inconsistent use of tabs and spaces in indentation (zmanager_facade.py, line 21)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/digitalpy/core/health, with error: inconsistent use of tabs and spaces in indentation (health_facade.py, line 21)
failed to register component: /home/pi/tak/lib/python3.9/site-packages/FreeTAKServer/core/data_package, with error: module 'FreeTAKServer.core.data_package.data_package_facade' has no attribute 'DataPackage'
failed to register component: /home/pi/tak/lib/python3.9/site-packages/FreeTAKServer/core/domain, with error: module 'FreeTAKServer.core.domain.domain_facade' has no attribute 'Domain'
failed to register component: /home/pi/tak/lib/python3.9/site-packages/FreeTAKServer/core/fts_configuration, with error: module 'FreeTAKServer.core.fts_configuration.fts_configuration_facade' has no attribute 'FtsConfiguration'
failed to register component: /home/pi/tak/lib/python3.9/site-packages/FreeTAKServer/core/fts_core, with error: module 'FreeTAKServer.core.fts_core.fts_core_facade' has no attribute 'FtsCore'
initiate_sockets
listening
listening
listening
start 213
starting now
running api
0.0.0.0
8080
(49946) wsgi starting up on http://0.0.0.0:8080
start 213
starting SSL now
0.0.0.0
8443
(49954) wsgi starting up on https://0.0.0.0:8443
CoTService started
CoTService started
{}
number of CoT messages received by services: 0
server started
mainRunFunction is running
client dict: {}
ssl cot service starting
started federation federate service
server started

<img width="1059" alt="Снимок экрана 2023-03-31 в 00 20 28" src="https://user-images.githubusercontent.com/53187739/228967549-66a2f5fb-b9a1-4b22-bfa3-f31f46bd8141.png">

**Comment by brothercorvo** [comment]
trying to fix the missing components with autopep8 is not going to work, in any case those are not missing components but an effect of our generator being not perfect. You can simply ignore those errors.

the main issue here is probably that you have the wrong IP so that the UI cannot communicate with the backend.
check also the logs or the console output.

**Comment by iAcolyte** [comment]
Hi, Corvo. It can see the server, and if it not - it has no server info.
Also I tried on raspberry pi so, it is localhost, and I'm sure it right
<img width="1021" alt="Снимок экрана 2023-04-03 в 18 17 30" src="https://user-images.githubusercontent.com/53187739/229553890-45b35b95-f8ad-48f5-b3eb-1552fef24e2f.png">

And it is log. I use custom docker container, but have the same issue on my raspberry.
[logs.log](https://github.com/FreeTAKTeam/DigitalPy/files/11139790/logs.log)

**Comment by brothercorvo** [comment]
127.0.0.1 is not a good way to set IPs. Try to use 0.0.0.0
Also, if you use your custom docker container we cannot help you

**Comment by iAcolyte** [comment]
> 127.0.0.1 is not a good way to set IPs. Try to use 0.0.0.0
> Also, if you use your custom docker container we cannot help you

Yep, I understand. That's why I was try it on the Raspberry PI and have the same issue. I set 0.0.0.0 in config file of FTS, so it isn't a problem, I suppose.

**Comment by brothercorvo** [comment]
this should be solved.
